# Generated by Django 3.0 on 2019-12-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldencrypt',
            name='char_file',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
