# Generated by Django 3.0 on 2019-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_char', models.CharField(max_length=500)),
                ('file_upload', models.FileField(upload_to='files')),
            ],
        ),
    ]
